"""add_company_settings

Revision ID: 38c7e388048d
Revises: e506b5f0bc88
Create Date: 2026-06-25 18:20:30.671962

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '38c7e388048d'
down_revision: Union[str, None] = 'e506b5f0bc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
