"""add variant_id to purchase_return_items

Revision ID: 483056287b4a
Revises: fc4854c5fff7
Create Date: 2026-06-30 17:26:56.362457

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '483056287b4a'
down_revision: Union[str, None] = 'fc4854c5fff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_return_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_return_items', 'product_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_return_items', type_='foreignkey')
    op.drop_column('purchase_return_items', 'variant_id')
    # ### end Alembic commands ###
