"""add variant_id to sales_invoice_items

Revision ID: 9b40dc37a173
Revises: cea731669982
Create Date: 2026-06-30 16:07:33.265270

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9b40dc37a173'
down_revision: Union[str, None] = 'cea731669982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_invoice_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales_invoice_items', 'product_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_invoice_items', type_='foreignkey')
    op.drop_column('sales_invoice_items', 'variant_id')
    # ### end Alembic commands ###
