"""add_company_settings

Revision ID: a716bc43f970
Revises: 38c7e388048d
Create Date: 2026-06-25 18:30:06.713063

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a716bc43f970'
down_revision: Union[str, None] = '38c7e388048d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
