"""add variant_id to sales_return_items

Revision ID: cea731669982
Revises: 86e55ba69374
Create Date: 2026-06-30 11:54:17.813811

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cea731669982'
down_revision: Union[str, None] = '86e55ba69374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_return_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales_return_items', 'product_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_return_items', type_='foreignkey')
    op.drop_column('sales_return_items', 'variant_id')
    # ### end Alembic commands ###
