"""add company settings

Revision ID: e506b5f0bc88
Revises: f1b91abbb505
Create Date: 2026-06-25 18:03:17.786701

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e506b5f0bc88'
down_revision: Union[str, None] = 'f1b91abbb505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('state_code', sa.String(length=5), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=12), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=30), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=10), nullable=False),
    sa.Column('invoice_terms', sa.String(length=500), nullable=True),
    sa.Column('invoice_footer', sa.String(length=300), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_settings')
    # ### end Alembic commands ###
