"""add_trade_pricing

Revision ID: f1b91abbb505
Revises: 7c6c23756e58
Create Date: 2026-06-23 05:37:16.107845

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f1b91abbb505'
down_revision: Union[str, None] = '7c6c23756e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('product_variants', sa.Column('trade_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('product_variants', 'price')
    op.add_column('users', sa.Column('is_trade_approved', sa.Boolean(), nullable=True, server_default='false'))
    op.execute("UPDATE users SET is_trade_approved = false WHERE is_trade_approved IS NULL")
    op.alter_column('users', 'is_trade_approved', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_trade_approved')
    op.add_column('product_variants', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('product_variants', 'trade_price')
    op.drop_column('product_variants', 'retail_price')
    # ### end Alembic commands ###
