"""add_opening_balance_voucher_type

Revision ID: f666098af449
Revises: b3f2e1d9c8a7
Create Date: 2026-06-28 18:48:49.579402

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f666098af449'
down_revision: Union[str, None] = 'b3f2e1d9c8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_transactions_variant_id', table_name='stock_transactions')
    op.drop_table('stock_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('txn_type', postgresql.ENUM('in', 'out', 'adjustment', name='stocktxntype'), autoincrement=False, nullable=False),
    sa.Column('qty_change', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qty_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qty_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='stock_transactions_created_by_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name='stock_transactions_variant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stock_transactions_pkey')
    )
    op.create_index('ix_stock_transactions_variant_id', 'stock_transactions', ['variant_id'], unique=False)
    # ### end Alembic commands ###
