"""make invoice_id nullable on sales_returns

Revision ID: fc4854c5fff7
Revises: 9b40dc37a173
Create Date: 2026-06-30 17:17:43.500020

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fc4854c5fff7'
down_revision: Union[str, None] = '9b40dc37a173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_returns', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_returns', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
